version: '3.4'

volumes:
  mongo_data:

services:
  catalog.api:
    container_name: catalog.api
    depends_on: 
    - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - MONGO_HOST=catalogdb
      - MONGO_PORT=27017
      - MONGO_DATABASE=ProductDb
      - MONGO_COLLECTION=Products 
    ports:
      - "8765:80"
      - "8766:443"
  
  catalogdb:
    container_name: catalogdb
    restart: always
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db
    
  basketdb:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - REDIS_HOST=basketdb
      - REDIS_PORT=6379
    ports:
    - "7000:7000"