version: '3.4'

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

services:
  catalog.api:
    container_name: catalog.api
    depends_on: 
    - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - MONGO_HOST=catalogdb
      - MONGO_PORT=27017
      - MONGO_DATABASE=ProductDb
      - MONGO_COLLECTION=Products 
    ports:
      - "8765:80"
      - "8766:443"
  
  catalogdb:
    container_name: catalogdb
    restart: always
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db
    
  discountdb:
    image: postgres
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"

  
  basketdb:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ce
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - REDIS_HOST=basketdb
      - REDIS_PORT=6379
    ports:
    - "7000:80"

  discount.api:
    container_name: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    environment:
      - POSTGRES_HOST=discountdb
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=admin
      - POSTGRES_DATABASE=DiscountDb
    depends_on:
      - discountdb
    ports:
      - "49155:80"  

  discount.grpc:
    container_name: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    environment:
      - POSTGRES_HOST=discountdb
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=admin
      - POSTGRES_DATABASE=DiscountDb
    depends_on:
      - discountdb
    ports:
      - "49160:80"

  orderdb:
    image: gapeevdi/orderdb:1
    container_name: orderdb
    environment:
      - SA_PASSWORD=admin1234
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1488:1433"

  ordering.api:
    container_name: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    environment:
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=admin1234"
    depends_on:
      - orderdb
    ports:
      - "49555:80"  
  